# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\a_bishe\code\Nodule-System-Python\src\ui\file\CadWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMainWindow


class CadWindowUI(QMainWindow):
    def __init__(self):
        super(CadWindowUI, self).__init__()
        self.setupUi(self)
        self.setWindowFlags(Qt.WindowMaximizeButtonHint | Qt.WindowMinimizeButtonHint | Qt.WindowCloseButtonHint)

        self.display_dialog = None
        # ColumnWidth of Patient List

        self.noduletreeWidget.setColumnWidth(0, 100)
        self.noduletreeWidget.setColumnWidth(1, 150)
        self.noduletreeWidget.setColumnWidth(2, 100)
        self.noduletreeWidget.setColumnWidth(3, 150)
        self.noduletreeWidget.setColumnWidth(4, 150)
        self.noduletreeWidget.setColumnWidth(5, 150)
        self.noduletreeWidget.setColumnWidth(6, 150)
        self.noduletreeWidget.setColumnWidth(7, 100)
        self.noduletreeWidget.setColumnHidden(7,True)
        # self.noduletreeWidget.header().setSectionResizeMode(QHeaderView.Stretch)
        # self.noduletreeWidget.header().setSectionResizeMode(QHeaderView.Interactive)

        self.treeWidget.setColumnWidth(0, 100)
        self.treeWidget.setColumnWidth(1, 70)
        self.treeWidget.setColumnWidth(2, 150)
        self.treeWidget.setColumnWidth(3, 150)
        self.treeWidget.setColumnWidth(4, 400)
        self.treeWidget.setColumnWidth(5, 70)

        # ColumnWidth of Scan and Nodule List

        # self.noduletreeWidget.setColumnWidth(8, 100)
        self.preferences_dialog = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 536)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.loadDicomButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadDicomButton.setObjectName("loadDicomButton")
        self.gridLayout.addWidget(self.loadDicomButton, 0, 3, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.treeWidget = QtWidgets.QTreeWidget(self.splitter)
        self.treeWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.treeWidget.setProperty("showDropIndicator", True)
        self.treeWidget.setAutoExpandDelay(-1)
        self.treeWidget.setIndentation(20)
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setUniformRowHeights(True)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setWordWrap(True)
        self.treeWidget.setHeaderHidden(False)
        self.treeWidget.setExpandsOnDoubleClick(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.treeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        self.treeWidget.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        self.treeWidget.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        self.treeWidget.headerItem().setTextAlignment(4, QtCore.Qt.AlignCenter)
        self.treeWidget.headerItem().setTextAlignment(5, QtCore.Qt.AlignCenter)
        self.treeWidget.header().setVisible(True)
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(100)
        self.treeWidget.header().setMinimumSectionSize(50)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(True)
        self.noduletreeWidget = QtWidgets.QTreeWidget(self.splitter)
        self.noduletreeWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.noduletreeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.noduletreeWidget.setProperty("showDropIndicator", True)
        self.noduletreeWidget.setAutoExpandDelay(-1)
        self.noduletreeWidget.setIndentation(20)
        self.noduletreeWidget.setRootIsDecorated(True)
        self.noduletreeWidget.setUniformRowHeights(True)
        self.noduletreeWidget.setItemsExpandable(True)
        self.noduletreeWidget.setAnimated(True)
        self.noduletreeWidget.setWordWrap(True)
        self.noduletreeWidget.setObjectName("noduletreeWidget")
        self.noduletreeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.noduletreeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        self.noduletreeWidget.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        self.noduletreeWidget.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        self.noduletreeWidget.headerItem().setTextAlignment(4, QtCore.Qt.AlignCenter)
        self.noduletreeWidget.headerItem().setTextAlignment(5, QtCore.Qt.AlignCenter)
        self.noduletreeWidget.headerItem().setTextAlignment(6, QtCore.Qt.AlignCenter)
        self.noduletreeWidget.headerItem().setTextAlignment(7, QtCore.Qt.AlignCenter)
        self.noduletreeWidget.header().setVisible(True)
        self.noduletreeWidget.header().setCascadingSectionResizes(False)
        self.noduletreeWidget.header().setDefaultSectionSize(120)
        self.noduletreeWidget.header().setMinimumSectionSize(50)
        self.noduletreeWidget.header().setSortIndicatorShown(False)
        self.noduletreeWidget.header().setStretchLastSection(True)
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 5)
        self.displayButton = QtWidgets.QPushButton(self.centralwidget)
        self.displayButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.displayButton.setObjectName("displayButton")
        self.gridLayout.addWidget(self.displayButton, 0, 4, 1, 1)
        self.addUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.addUserButton.setObjectName("addUserButton")
        self.gridLayout.addWidget(self.addUserButton, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menubar.setObjectName("menubar")
        self.menuNodule_CADx = QtWidgets.QMenu(self.menubar)
        self.menuNodule_CADx.setObjectName("menuNodule_CADx")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.action22213123 = QtWidgets.QAction(MainWindow)
        self.action22213123.setObjectName("action22213123")
        self.addUserAction = QtWidgets.QAction(MainWindow)
        self.addUserAction.setObjectName("addUserAction")
        self.menubar.addAction(self.menuNodule_CADx.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "肺结节智能分析系统"))
        self.loadDicomButton.setText(_translate("MainWindow", "添加影像"))
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "姓名"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "性别"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "生日"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "联系电话"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "备注信息"))
        self.treeWidget.headerItem().setText(5, _translate("MainWindow", "操作"))
        self.noduletreeWidget.setSortingEnabled(False)
        self.noduletreeWidget.headerItem().setText(0, _translate("MainWindow", "状态"))
        self.noduletreeWidget.headerItem().setText(1, _translate("MainWindow", "检测时间"))
        self.noduletreeWidget.headerItem().setText(2, _translate("MainWindow", "检测年龄"))
        self.noduletreeWidget.headerItem().setText(3, _translate("MainWindow", "概率"))
        self.noduletreeWidget.headerItem().setText(4, _translate("MainWindow", "直径"))
        self.noduletreeWidget.headerItem().setText(5, _translate("MainWindow", "类别"))
        self.noduletreeWidget.headerItem().setText(6, _translate("MainWindow", "恶性概率"))
        self.noduletreeWidget.headerItem().setText(7, _translate("MainWindow", "信息"))
        self.displayButton.setText(_translate("MainWindow", "查看"))
        self.addUserButton.setText(_translate("MainWindow", "添加患者"))
        self.menuNodule_CADx.setTitle(_translate("MainWindow", "菜单"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.action22213123.setText(_translate("MainWindow", "File"))
        self.addUserAction.setText(_translate("MainWindow", "添加患者"))

if __name__ == "__main__":

    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = CadWindowUI()
    ui.show()
    sys.exit(app.exec_())