# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\a_bishe\code\Nodule-System-Python\client\ui\file\add_scan.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class AddScanDialogUI(QDialog):

    def __init__(self):
        super(AddScanDialogUI, self).__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(525, 416)
        Dialog.setMinimumSize(QtCore.QSize(525, 300))
        icon = QtGui.QIcon()
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("color: rgb(200, 200, 200);\n"
                             "background-color: rgb(10, 10, 10);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setStyleSheet("border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.login_area_2 = QtWidgets.QFrame(self.frame_3)
        self.login_area_2.setMaximumSize(QtCore.QSize(500, 600))
        self.login_area_2.setStyleSheet("border-radius: 10px;")
        self.login_area_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area_2.setObjectName("login_area_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.login_area_2)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_2.setVerticalSpacing(30)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_15 = QtWidgets.QLabel(self.login_area_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.nameEdit = QtWidgets.QLineEdit(self.login_area_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.nameEdit.setFont(font)
        self.nameEdit.setStyleSheet("QLineEdit {\n"
                                    "    border: 2px solid rgb(45, 45, 45);\n"
                                    "    border-radius: 5px;\n"
                                    "    padding: 5px;\n"
                                    "    background-color: rgb(30, 30, 30);    \n"
                                    "    color: rgb(100, 100, 100);\n"
                                    "}\n"
                                    "QLineEdit:hover {\n"
                                    "    border: 2px solid rgb(55, 55, 55);\n"
                                    "}\n"
                                    "QLineEdit:focus {\n"
                                    "    border: 2px solid rgb(170, 255, 255);    \n"
                                    "    color: rgb(200, 200, 200);\n"
                                    "}")
        self.nameEdit.setText("")
        self.nameEdit.setMaxLength(32)
        self.nameEdit.setReadOnly(True)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.label_16 = QtWidgets.QLabel(self.login_area_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.frame_5 = QtWidgets.QFrame(self.login_area_2)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(5)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.filePathEdit = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.filePathEdit.setFont(font)
        self.filePathEdit.setStyleSheet("QLineEdit {\n"
                                        "    border: 2px solid rgb(45, 45, 45);\n"
                                        "    border-radius: 5px;\n"
                                        "    padding: 5px;\n"
                                        "    background-color: rgb(30, 30, 30);    \n"
                                        "    color: rgb(100, 100, 100);\n"
                                        "}\n"
                                        "QLineEdit:hover {\n"
                                        "    border: 2px solid rgb(55, 55, 55);\n"
                                        "}\n"
                                        "QLineEdit:focus {\n"
                                        "    border: 2px solid rgb(170, 255, 255);    \n"
                                        "    color: rgb(200, 200, 200);\n"
                                        "}")
        self.filePathEdit.setText("")
        self.filePathEdit.setMaxLength(3276)
        self.filePathEdit.setReadOnly(False)
        self.filePathEdit.setObjectName("filePathEdit")
        self.horizontalLayout_13.addWidget(self.filePathEdit)
        self.filePathButton = QtWidgets.QPushButton(self.frame_5)
        self.filePathButton.setStyleSheet("QPushButton {    \n"
                                          "    background-color: rgb(50, 50, 50);\n"
                                          "    border: 2px solid rgb(60, 60, 60);\n"
                                          "padding: 5px;\n"
                                          "    border-radius: 5px;\n"
                                          "}\n"
                                          "QPushButton:hover {    \n"
                                          "    background-color: rgb(60, 60, 60);\n"
                                          "    border: 2px solid rgb(70, 70, 70);\n"
                                          "}\n"
                                          "QPushButton:pressed {    \n"
                                          "    background-color: rgb(170, 255, 255);\n"
                                          "    border: 2px solid rgb(255, 165, 24);    \n"
                                          "    color: rgb(35, 35, 35);\n"
                                          "}")
        self.filePathButton.setObjectName("filePathButton")
        self.horizontalLayout_13.addWidget(self.filePathButton)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.frame_5)
        self.label_12 = QtWidgets.QLabel(self.login_area_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_4 = QtWidgets.QFrame(self.login_area_2)
        self.frame_4.setStyleSheet("QFrame {\n"
                                   "    border: 2px solid rgb(45, 45, 45);\n"
                                   "    border-radius: 5px;\n"
                                   "    background-color: rgb(30, 30, 30);    \n"
                                   "    color: rgb(100, 100, 100);\n"
                                   "}\n"
                                   "")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(5)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.MaleButton = QtWidgets.QRadioButton(self.frame_4)
        self.MaleButton.setStyleSheet("QRadioButton {\n"
                                      "    background-color: rgb(30, 30, 30);    \n"
                                      "    color: rgb(100, 100, 100);\n"
                                      "}\n"
                                      "")
        self.MaleButton.setCheckable(True)
        self.MaleButton.setChecked(True)
        self.MaleButton.setObjectName("MaleButton")
        self.horizontalLayout_11.addWidget(self.MaleButton)
        self.FemaleButton = QtWidgets.QRadioButton(self.frame_4)
        self.FemaleButton.setStyleSheet("QRadioButton {\n"
                                        "    background-color: rgb(30, 30, 30);    \n"
                                        "    color: rgb(100, 100, 100);\n"
                                        "}\n"
                                        "r")
        self.FemaleButton.setCheckable(True)
        self.FemaleButton.setObjectName("FemaleButton")
        self.horizontalLayout_11.addWidget(self.FemaleButton)
        self.horizontalLayout_12.addWidget(self.frame_4)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.label_14 = QtWidgets.QLabel(self.login_area_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.ageEdit = QtWidgets.QLineEdit(self.login_area_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.ageEdit.setFont(font)
        self.ageEdit.setStyleSheet("QLineEdit {\n"
                                   "    border: 2px solid rgb(45, 45, 45);\n"
                                   "    border-radius: 5px;\n"
                                   "    padding: 5px;\n"
                                   "    background-color: rgb(30, 30, 30);    \n"
                                   "    color: rgb(100, 100, 100);\n"
                                   "}\n"
                                   "QLineEdit:hover {\n"
                                   "    border: 2px solid rgb(55, 55, 55);\n"
                                   "}\n"
                                   "QLineEdit:focus {\n"
                                   "    border: 2px solid rgb(170, 255, 255);    \n"
                                   "    color: rgb(200, 200, 200);\n"
                                   "}")
        self.ageEdit.setText("")
        self.ageEdit.setMaxLength(32)
        self.ageEdit.setObjectName("ageEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ageEdit)
        self.label_13 = QtWidgets.QLabel(self.login_area_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 33))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.login_area_2)
        self.dateTimeEdit.setStyleSheet("QDateTimeEdit {\n"
                                        "    border: 2px solid rgb(45, 45, 45);\n"
                                        "    border-radius: 5px;\n"
                                        "    padding: 5px;\n"
                                        "    background-color: rgb(30, 30, 30);    \n"
                                        "    color: rgb(100, 100, 100);\n"
                                        "}\n"
                                        "QDateTimeEdit:hover {\n"
                                        "    border: 2px solid rgb(55, 55, 55);\n"
                                        "}\n"
                                        "QDateTimeEdit:focus {\n"
                                        "    border: 2px solid rgb(170, 255, 255);    \n"
                                        "    color: rgb(200, 200, 200);\n"
                                        "}")
        self.dateTimeEdit.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 3, 14), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.uploadButton = QtWidgets.QPushButton(self.login_area_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.uploadButton.setFont(font)
        self.uploadButton.setStyleSheet("QPushButton {    \n"
                                        "    background-color: rgb(50, 50, 50);\n"
                                        "    border: 2px solid rgb(60, 60, 60);\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "QPushButton:hover {    \n"
                                        "    background-color: rgb(60, 60, 60);\n"
                                        "    border: 2px solid rgb(70, 70, 70);\n"
                                        "}\n"
                                        "QPushButton:pressed {    \n"
                                        "    background-color: rgb(170, 255, 255);\n"
                                        "    border: 2px solid rgb(255, 165, 24);    \n"
                                        "    color: rgb(35, 35, 35);\n"
                                        "}")
        self.uploadButton.setObjectName("uploadButton")
        self.verticalLayout_4.addWidget(self.uploadButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6.addWidget(self.login_area_2)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "上传影像"))
        self.label_15.setText(_translate("Dialog", "姓名"))
        self.nameEdit.setPlaceholderText(_translate("Dialog", "姓名"))
        self.label_16.setText(_translate("Dialog", "文件地址"))
        self.filePathEdit.setPlaceholderText(_translate("Dialog", "DICOM文件夹地址"))
        self.filePathButton.setText(_translate("Dialog", "选择文件夹"))
        self.label_12.setText(_translate("Dialog", "性别"))
        self.MaleButton.setText(_translate("Dialog", "男性"))
        self.FemaleButton.setText(_translate("Dialog", "女性"))
        self.label_14.setText(_translate("Dialog", "年龄"))
        self.ageEdit.setPlaceholderText(_translate("Dialog", "年龄"))
        self.label_13.setText(_translate("Dialog", "检测时间"))
        self.uploadButton.setText(_translate("Dialog", "上传"))
